spring:
  application:
    name: dubbo-consumer

server:
  port: 8082

dubbo:
  registry:
    address: nacos://127.0.0.1:8848 #注册地址
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo #dubbo协议
    port: 20882 #协议端口