spring:
  application:
    name: dubbo-provider

server:
  port: 8081

dubbo:
  registry:
    address: nacos://127.0.0.1:8848 #注册地址
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo #dubbo协议
    port: 20881 #协议端口
  scan:
    base-packages: com.github.qjerry.service.impl #扫包范围
  provider:
    timeout: 30000 #超时时间